export const data = [
    {
        coordinate: [-34.74317133345502, -58.38993950186129],
        provincia: 'buenos_aires',
        localidad: 'banfield',
        tipo: 'alojamiento',
        data: {
            nombre: 'Proyecto Mas',
            descripcion: 'descripcion del Proyecto Max',
            contacto: 'Agüero Garcia, Ayelén Lourdes',
            num_contacto: '+011 1125-4521',
            mail: 'ayelen97aguero@gmail.com',
            entrevista: false,
            forms: true,
            estrato: '5-6',
            quienContacto: 'Santiago',
            fechaEntrevista: 'Mensaje enviado 10/10/2023',
            organizacion: 'Organización Social',
            linkInfo: 'https://onpsc.untref.edu.ar/es/home',
            linkInterno: 'https://onpsc.untref.edu.ar/es/home',
            linkInterno: null,
        },
    },
    {
        coordinate: [-38.04394750726469, -57.59144060643585],
        provincia: 'buenos_aires',
        localidad: 'mar_del_plata',
        tipo: 'alojamiento',
        data: {
            nombre: 'Censos',
            descripcion: 'descripcion del Censos',
            contacto: 'Sad, Facundo',
            num_contacto: '+011 0025-1111',
            mail: 'fsad1010@gmail.com',
            entrevista: false,
            forms: false,
            estrato: '5-6',
            quienContacto: 'Santiago',
            fechaEntrevista: 'Mensaje enviado 10/10/2023',
            organizacion: 'Organización Social',
            linkInfo: 'https://onpsc.untref.edu.ar/es/home',
            linkInterno: 'https://onpsc.untref.edu.ar/es/home',
        },
    },
    {
        coordinate: [-38.08535808505526, -57.595935406967676],
        provincia: 'buenos_aires',
        localidad: 'mar_del_plata',
        tipo: 'salud',
        data: {
            nombre: 'COMUNIDADES DEL SUR - Don Orione',
            descripcion: 'descripcion del COMUNIDADES DEL SUR - Don Orione',
            contacto: 'Gutierrez, Alejo Daniel',
            num_contacto: '+011 0100-1010',
            mail: 'gutierrez1010@hotmail.com',
            entrevista: true,
            forms: false,
            estrato: '5-6',
            quienContacto: 'Jor',
            fechaEntrevista: 'A confirmar miércoles o jueves',
            organizacion: 'Organismo Público',
            linkInfo: 'https://onpsc.untref.edu.ar/es/home',
            linkInterno: 'https://onpsc.untref.edu.ar/es/home',
        },
    },
    {
        coordinate: [-33.340772428131224, -60.22107941915559],
        provincia: 'buenos_aires',
        localidad: 'san_nicolas_de_los_arroyos',
        tipo: 'salud',
        data: {
            nombre: 'La Casita de Don Orione Un hogar para todos',
            descripcion: 'descripcion del Proyecto Max',
            contacto: 'Perez, Julia Daniela',
            num_contacto: '',
            mail: 'casitadonorione@hotmail.com',
            entrevista: false,
            forms: false,
            estrato: '5-6',
            quienContacto: 'Mabel',
            fechaEntrevista: 'A confirmar',
            organizacion: 'Organismo Público',
            linkInfo: 'https://onpsc.untref.edu.ar/es/home',
            linkInterno: null,
        },
    },
    {
        coordinate: [-29.14662871017508, -59.63440941489629],
        provincia: 'santa_fe',
        localidad: 'reconquista',
        tipo: 'higiene',
        data: {
            nombre: 'LOS CORTADEÑOS',
            descripcion: 'descripcion del LOS CORTADEÑOS',
            contacto: 'Perez, Julia Daniela',
            num_contacto: '',
            mail: 'casitadonorione@hotmail.com',
            entrevista: false,
            forms: false,
            estrato: '5-6',
            quienContacto: 'Lucía',
            fechaEntrevista: 'Mensaje enviado 10/01/2023',
            organizacion: 'Organismo Privado',
            linkInfo: 'https://onpsc.untref.edu.ar/es/home',
            linkInterno: 'https://onpsc.untref.edu.ar/es/home',
        },
    },
    {
        coordinate: [-27.473908430391607, -59.01214432071524],
        provincia: 'chaco',
        localidad: 'resistencia',
        tipo: 'higiene',
        data: {
            nombre: 'CORAZÓN AMIGO',
            descripcion: 'descripcion del CORAZÓN AMIGO',
            contacto: 'Cusco, Javier',
            num_contacto: '+011 0100-9090',
            mail: 'amigodelcoazon@yahoo.com',
            entrevista: false,
            forms: false,
            estrato: '5-6',
            quienContacto: 'Martín',
            fechaEntrevista: 'Mail enviado 10/12/2022',
            organizacion: 'Organismo Privado',
            linkInfo: null,
            linkInterno: 'https://onpsc.untref.edu.ar/es/home',
        },
    },
    {
        coordinate: [-23.812945916463313, -64.79712449468718],
        provincia: 'jujuy',
        localidad: 'libertador_general_san_martin',
        tipo: 'alimentacion',
        data: {
            nombre: 'CENTRO LIBERTAD',
            descripcion: 'descripcion del CENTRO LIBERTAD',
            contacto: 'Gomez, Nicolás',
            num_contacto: '+011 0100-9090',
            mail: 'amigodelcoazon@yahoo.com',
            entrevista: false,
            forms: false,
            estrato: '5-6',
            quienContacto: 'Martín',
            fechaEntrevista: 'Mail enviado 09/10/2023',
            organizacion: '',
            linkInfo: null,
            linkInterno: null,
        }
    },
    {
        coordinate: [-24.707747650774493, -60.58868413449087],
        provincia: 'formosa',
        localidad: 'las_lomitas',
        tipo: 'alimentacion',
        data: {
            nombre: 'ASOCIACIÓN PARA LA PROMOCIÓN DE LA CULTURA Y EL DESARROLLO',
            descripcion: 'descripcion del ASOCIACIÓN PARA LA PROMOCIÓN DE LA CULTURA Y EL DESARROLLO',
            contacto: 'Jackunas, Mauro',
            num_contacto: '+011 0100-9090',
            mail: 'culturaydesarrollo@yahoo.com',
            entrevista: true,
            forms: false,
            estrato: '5-6',
            quienContacto: 'Martín',
            fechaEntrevista: 'Mail enviado 27/04/2023',
            organizacion: 'Equipo de Investigación',
            linkInfo: null,
            linkInterno: 'https://onpsc.untref.edu.ar/es/home',
        }
    },
    {
        coordinate: [-31.54069031461898, -68.52747512168037],
        provincia: 'san_juan',
        localidad: 'san_juan',
        tipo: 'recorridos',
        data: {
            nombre: 'Refugio Madre Teresa de Calculta',
            descripcion: 'descripcion del Refugio Madre Teresa de Calculta',
            contacto: 'Godoy, Brenda',
            num_contacto: '+011 0122-1010',
            mail: 'culturaydesarrollo@yahoo.com',
            entrevista: true,
            forms: true,
            estrato: '5-6',
            quienContacto: 'Santiago',
            fechaEntrevista: 'Mail enviado 18/02/2023',
            organizacion: 'Equipo de Investigación',
            linkInfo: null,
            linkInterno: 'https://onpsc.untref.edu.ar/es/home',
        }
    },
    {
        coordinate: [-38.96534906483482, -68.06152514521344],
        provincia: 'neuquen',
        localidad: 'neuquen',
        tipo: 'recorridos',
        data: {
            nombre: 'Refugio Cura Brochero',
            descripcion: 'descripcion del Refugio Cura Brochero',
            contacto: 'Fernando, Martina',
            num_contacto: '+011 0122-1010',
            mail: 'curafernandez@yahoo.com',
            entrevista: true,
            forms: true,
            estrato: '5-6',
            quienContacto: 'Mabel',
            fechaEntrevista: 'Mensaje enviado 12/10/2023',
            organizacion: 'Otro',
            linkInfo: 'https://onpsc.untref.edu.ar/es/home',
            linkInterno: 'https://onpsc.untref.edu.ar/es/home',
        }
    },
];