export const data = [
    {
        coordinate: [-34.74317133345502, -58.38993950186129],
        provincia: 'buenos_aires',
        localidad: 'banfield',
        tipo: 'org_social',
        data: {
            nombre: 'Proyecto Mas',
            observacion: 'observacion del Proyecto Max',
            contacto: 'Agüero Garcia, Ayelén Lourdes',
            num_contacto: '+011 1125-4521',
            mail: 'ayelen97aguero@gmail.com',
            entrevista: false,
            forms: true,
        },
    },
    {
        coordinate: [-38.04394750726469, -57.59144060643585],
        provincia: 'buenos_aires',
        localidad: 'mar_del_plata',
        tipo: 'org_publico',
        data: {
            nombre: 'Censos',
            observacion: 'observacion del Censos',
            contacto: 'Sad, Facundo',
            num_contacto: '+011 0025-1111',
            mail: 'fsad1010@gmail.com',
            entrevista: false,
            forms: false,
        },
    },
    {
        coordinate: [-38.08535808505526, -57.595935406967676],
        provincia: 'buenos_aires',
        localidad: 'mar_del_plata',
        tipo: 'org_privado',
        data: {
            nombre: 'COMUNIDADES DEL SUR - Don Orione',
            observacion: 'observacion del COMUNIDADES DEL SUR - Don Orione',
            contacto: 'Gutierrez, Alejo Daniel',
            num_contacto: '+011 0100-1010',
            mail: 'gutierrez1010@hotmail.com',
            entrevista: true,
            forms: false,
        },
    },
    {
        coordinate: [-33.340772428131224, -60.22107941915559],
        provincia: 'buenos_aires',
        localidad: 'san_nicolas_de_los_arroyos',
        tipo: 'org_publico',
        data: {
            nombre: 'La Casita de Don Orione Un hogar para todos',
            observacion: 'observacion del Proyecto Max',
            contacto: 'Perez, Julia Daniela',
            num_contacto: '',
            mail: 'casitadonorione@hotmail.com',
            entrevista: false,
            forms: false,
        },
    },
    {
        coordinate: [-29.14662871017508, -59.63440941489629],
        provincia: 'santa_fe',
        localidad: 'reconquista',
        tipo: 'org_social',
        data: {
            nombre: 'LOS CORTADEÑOS',
            observacion: 'observacion del LOS CORTADEÑOS',
            contacto: 'Perez, Julia Daniela',
            num_contacto: '',
            mail: 'casitadonorione@hotmail.com',
            entrevista: false,
            forms: false,
        },
    },
    {
        coordinate: [-27.473908430391607, -59.01214432071524],
        provincia: 'chaco',
        localidad: 'resistencia',
        tipo: 'org_publico',
        data: {
            nombre: 'CORAZÓN AMIGO',
            observacion: 'observacion del CORAZÓN AMIGO',
            contacto: 'Cusco, Javier',
            num_contacto: '+011 0100-9090',
            mail: 'amigodelcoazon@yahoo.com',
            entrevista: false,
            forms: false,
        },
    },
    {
        coordinate: [-23.812945916463313, -64.79712449468718],
        provincia: 'jujuy',
        localidad: 'libertador_general_san_martin',
        tipo: 'org_privado',
        data: {
            nombre: 'CENTRO LIBERTAD',
            observacion: 'observacion del CENTRO LIBERTAD',
            contacto: 'Gomez, Nicolás',
            num_contacto: '+011 0100-9090',
            mail: 'amigodelcoazon@yahoo.com',
            entrevista: false,
            forms: false,
        }
    },
    {
        coordinate: [-24.707747650774493, -60.58868413449087],
        provincia: 'formosa',
        localidad: 'las_lomitas',
        tipo: 'org_publico',
        data: {
            nombre: 'ASOCIACIÓN PARA LA PROMOCIÓN DE LA CULTURA Y EL DESARROLLO',
            observacion: 'observacion del ASOCIACIÓN PARA LA PROMOCIÓN DE LA CULTURA Y EL DESARROLLO',
            contacto: 'Jackunas, Mauro',
            num_contacto: '+011 0100-9090',
            mail: 'culturaydesarrollo@yahoo.com',
            entrevista: true,
            forms: false,
        }
    },
    {
        coordinate: [-31.54069031461898, -68.52747512168037],
        provincia: 'san_juan',
        localidad: 'san_juan',
        tipo: 'org_social',
        data: {
            nombre: 'Refugio Madre Teresa de Calculta',
            observacion: 'observacion del Refugio Madre Teresa de Calculta',
            contacto: 'Godoy, Brenda',
            num_contacto: '+011 0122-1010',
            mail: 'culturaydesarrollo@yahoo.com',
            entrevista: true,
            forms: true,
        }
    },
    {
        coordinate: [-38.96534906483482, -68.06152514521344],
        provincia: 'neuquen',
        localidad: 'neuquen',
        tipo: 'org_publico',
        data: {
            nombre: 'Refugio Cura Brochero',
            observacion: 'observacion del Refugio Cura Brochero',
            contacto: 'Fernando, Martina',
            num_contacto: '+011 0122-1010',
            mail: 'curafernandez@yahoo.com',
            entrevista: true,
            forms: true,
        }
    },
];